[tools]
usage = "3.5.0"
bun = "1.4.0"
node = "26.8.1"
"npm:agent-browser" = "0.27.3"
btop = "1.4.7"
bottom = "0.14.9"
starship = "1.26.0"
bat = "0.26.1"
bat-extras = "2024.08.24"
ripgrep-all = "0.10.10"
ripgrep = "15.2.0"
"npm:effect-solutions" = "0.5.3"
tree-sitter = "0.26.9"
"npm:@effect/language-service" = "0.86.2"
rust = { version = "1.98.0", components = ["rust-analyzer"] }
"npm:@steipete/summarize" = "0.18.1"
"cargo:lstr" = "0.2.1"
uv = "0.12.7"
"pipx:yt-dlp" = "2026.6.9"
glow = "2.1.2"
"npm:@openai/codex" = "0.144.5"
chezmoi = "2.70.5"
pnpm = "12.1.0"
kubectl = "1.36.2"
kubelogin = "1.36.2"
restic = "0.19.0"
"npm:@kitlangton/ghui" = "0.7.1"
"npm:hunkdiff" = "0.16.0"
fd = "10.5.0"
eza = "0.23.5"
lazygit = "0.64.1"
gh = "2.94.0"
pi = "0.85.1"
fzf = "0.74.3"
jq = "1.8.2"
superfile = "1.6.0"
"npm:mcporter" = "0.12.3"
"github:agavra/tuicr" = "0.21.0"
"aqua:pimalaya/himalaya" = "2.0.0"
workmux = "0.1.237"
"cargo:rustic-rs" = "0.11.3"
gitleaks = "8.30.1"
trufflehog = "3.97.1"
"cargo:rustlings" = "6.5.0"
"npm:@deepseek-ai/dsh" = "0.1.1-rc.2"
"cargo:dioxus-cli" = "0.7.10"

[settings]
minimum_release_age = "7d"
minimum_release_age_excludes = ["pi"]

[settings.npm]
package_manager = "bun"

[env]
XDG_CONFIG_HOME = "/home/knth/.config"
XDG_DATA_HOME = "/home/knth/.local/share"
XDG_CACHE_HOME = "/home/knth/.cache"
XDG_STATE_HOME = "/home/knth/.local/state"
